remote_theme: pmarsceill/just-the-docs
logo: img/logo.svg
ga_tracking: UA-23493957-4
ga_publisher: pub-3600741293730423
title: VueGL
description: Vue.js components rendering 3D WebGL graphics reactively with Three.js
aux_links:
  View project on GitHub: //github.com/vue-gl/vue-gl
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - rollup.config.js
